### ISSUE TITLE
[Feature Request] Add Currency Check Support

### ISSUE THREAD

**Issue by piasticOuO** [AuroraNetworkStudios/AuroraQuests#7]
I find it difficult to make quests like "Earn 500 coins to unlock the next stage" and currently need workarounds now.

Would you consider adding native support for currency checks? Like this:

```
  your_task_id:
    task: MONEY
    display: "{status} &fHave {required} money &b{current}&f/&b{required}"
    args:
      # How many money should the player have?
      amount: 10000
```

And maybe we can add more task types like EARN_MONEY?
